/*
 * File: MyViewport.ui.js
 * Date: Wed May 02 2012 18:33:11 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MyViewportUi = Ext.extend(Ext.Viewport, {
    layout: 'border',
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                region: 'north',
                width: 100,
                height: 100,
                unstyled: true,
                ref: 'pnlSuperior',
                tbar: {
                    xtype: 'toolbar',
                    height: 80,
                    items: [
                        {
                            xtype: 'button',
                            text: 'Menú Principal',
                            scale: 'large',
                            icon: 'http://expresso/dashboard01/imagenes/home.png',
                            iconAlign: 'top',
                            tooltip: 'Menú principal',
                            width: 70
                        },
                        {
                            xtype: 'tbseparator',
                            width: 30
                        },
                        {
                            xtype: 'button',
                            text: 'Ayuda',
                            scale: 'large',
                            icon: 'http://expresso/dashboard01/imagenes/help.png',
                            iconAlign: 'top'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            text: 'Chat&nbsp;&nbsp;',
                            icon: 'http://expresso/dashboard01/imagenes/chat_bubble.png',
                            scale: 'large',
                            iconAlign: 'top',
                            width: 40
                        },
                        {
                            xtype: 'button',
                            text: 'Preferencias',
                            scale: 'large',
                            icon: 'http://expresso/dashboard01/imagenes/favorites.png',
                            iconAlign: 'top'
                        },
                        {
                            xtype: 'button',
                            text: '&nbsp;&nbsp;&nbsp;Salir&nbsp; &nbsp;&nbsp;&nbsp;',
                            scale: 'large',
                            iconAlign: 'top',
                            icon: 'http://expresso/dashboard01/imagenes/logout.png'
                        }
                    ]
                }
            },
            {
                xtype: 'tabpanel',
                activeTab: 0,
                region: 'center',
                items: [
                    {
                        xtype: 'panel',
                        title: 'Menu',
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'panel',
                                iconCls: 'tab_icon_home',
                                layout: 'border',
                                items: [
                                    {
                                        xtype: 'panel',
                                        region: 'center',
                                        width: 400
                                    },
                                    {
                                        xtype: 'panel',
                                        region: 'west',
                                        width: 500,
                                        autoScroll: true,
                                        items: [
                                            {
                                                xtype: 'dataview',
                                                itemSelector: 'div',
                                                tpl: '<tpl for="."><div>Template</div></tpl>',
                                                width: 500,
                                                autoScroll: true,
                                                ref: '../../../../dtvMenu'
                                            }
                                        ],
                                        tbar: {
                                            xtype: 'toolbar',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    text: 'Ver como arbol'
                                                }
                                            ]
                                        }
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        title: 'Tab 2'
                    },
                    {
                        xtype: 'panel',
                        title: 'Tab 3'
                    },
                    {
                        xtype: 'panel',
                        title: 'My Tab'
                    }
                ]
            }
        ];
        MyViewportUi.superclass.initComponent.call(this);
    }
});
