/*
 * File: MyViewport.js
 * Date: Tue May 01 2012 04:39:52 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

MyViewport = Ext.extend(MyViewportUi, {
    initComponent: function() {
        MyViewport.superclass.initComponent.call(this);
		var store = new Ext.data.JsonStore({
			url: 'get-images.php',
			root: 'images',
			fields: [
				'name', 'icon','shortName',
				{name:'size', type: 'float'}				
			]
		});
		store.load()

		var tpl = new Ext.XTemplate(
			'<tpl for=".">',
				'<div class="menu_wrap"><div class="thumb-wrap" id="{name}">',
				'<div class="thumb"><img src="{icon}" title="{name}"></div>',
				'<span class="x-editable">{shortName}</span></div></div>',
			'</tpl>',
			'<div class="x-clear"></div>'
		);
		
		Ext.apply(this.dtvMenu,{
			store: store,
			tpl: tpl,
			autoHeight:true,
			multiSelect: true,
			overClass:'x-view-over',
			itemSelector:'div.thumb-wrap',
			emptyText: 'No images to display'
		});		
		
		
    }
});
