/*
 * File: gridEdicionHorarios.js
 * Date: Sat May 12 2012 17:33:10 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

gridEdicionHorarios = Ext.extend(gridEdicionHorariosUi, {
    initComponent: function() {
        gridEdicionHorarios.superclass.initComponent.call(this);
    }
});
Ext.reg('gridEdicionHorarios', gridEdicionHorarios);