/*
 * File: gridEdicionHorarios.ui.js
 * Date: Sat May 12 2012 17:36:29 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

gridEdicionHorariosUi = Ext.extend(Ext.grid.EditorGridPanel, {
    width: 400,
    height: 250,
    initComponent: function() {
        this.columns = [
            {
                xtype: 'gridcolumn',
                dataIndex: 'horaInicio',
                header: 'Hora Encendido',
                sortable: true,
                width: 100,
                align: 'right',
                editor: {
                    xtype: 'timefield'
                }
            },
            {
                xtype: 'numbercolumn',
                dataIndex: 'horaFin',
                header: 'Hora Apagado',
                sortable: true,
                width: 100,
                align: 'right',
                editor: {
                    xtype: 'timefield'
                }
            }
        ];
        this.view = new Ext.grid.GridView({
            autoFill: true
        });
        gridEdicionHorariosUi.superclass.initComponent.call(this);
    }
});
